/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vocode from "../../../../api/index";
import * as core from "../../../../core";
import { AgentParams } from "../../../types/AgentParams";

export const BuyPhoneNumberRequestInboundAgent: core.serialization.Schema<
    serializers.BuyPhoneNumberRequestInboundAgent.Raw,
    Vocode.BuyPhoneNumberRequestInboundAgent
> = core.serialization.undiscriminatedUnion([
    AgentParams,
    core.serialization.string(),
    core.serialization.stringLiteral("default"),
]);

export declare namespace BuyPhoneNumberRequestInboundAgent {
    type Raw = AgentParams.Raw | string | "default";
}
