/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vocode from "../../../../api/index";
import * as core from "../../../../core";
import { AgentUpdateParams } from "../../../types/AgentUpdateParams";
import { Undefined } from "../../../types/Undefined";

export const UpdateNumberRequestInboundAgent: core.serialization.Schema<
    serializers.UpdateNumberRequestInboundAgent.Raw,
    Vocode.UpdateNumberRequestInboundAgent
> = core.serialization.undiscriminatedUnion([AgentUpdateParams, core.serialization.string(), Undefined]);

export declare namespace UpdateNumberRequestInboundAgent {
    type Raw = AgentUpdateParams.Raw | string | Undefined.Raw;
}
