/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vocode from "../../../../api/index";
import * as core from "../../../../core";
import { Undefined } from "../../../types/Undefined";

export const UpdateNumberRequestOutboundOnly: core.serialization.Schema<
    serializers.UpdateNumberRequestOutboundOnly.Raw,
    Vocode.UpdateNumberRequestOutboundOnly
> = core.serialization.undiscriminatedUnion([core.serialization.boolean(), Undefined]);

export declare namespace UpdateNumberRequestOutboundOnly {
    type Raw = boolean | Undefined.Raw;
}
