/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vocode from "../../../../api/index";
import * as core from "../../../../core";
import { Undefined } from "../../../types/Undefined";

export const UpdateNumberRequestExampleContext: core.serialization.Schema<
    serializers.UpdateNumberRequestExampleContext.Raw,
    Vocode.UpdateNumberRequestExampleContext
> = core.serialization.undiscriminatedUnion([
    core.serialization.record(core.serialization.string(), core.serialization.string()),
    Undefined,
]);

export declare namespace UpdateNumberRequestExampleContext {
    type Raw = Record<string, string> | Undefined.Raw;
}
