/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {
 *         id: "id",
 *         body: undefined
 *     }
 */
export interface AddToSteeringPoolRequest {
    id: string;
    body?: Vocode.AddToSteeringPoolBody;
}
