/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id",
 *         phoneNumber: "phone_number"
 *     }
 */
export interface RemoveFromSteeringPoolRequest {
    id: string;
    phoneNumber: string;
}
