/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             type: "account_connection_openai"
 *         }
 *     }
 */
export interface UpdateAccountConnectionRequest {
    id: string;
    body: Vocode.AccountConnectionUpdateParamsRequest;
}
