/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {}
 *     }
 */
export interface UpdateWebhookRequest {
    id: string;
    body: Vocode.WebhookUpdateParams;
}
