/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             type: "vector_database_pinecone"
 *         }
 *     }
 */
export interface UpdateVectorDatabaseRequest {
    id: string;
    body: Vocode.PineconeVectorDatabaseUpdateParams;
}
