/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Vocode from "../../../../../api/index";
import * as core from "../../../../../core";
import { CreateCallRequestAgent } from "../../types/CreateCallRequestAgent";
import { CreateCallRequestOnNoHumanAnswer } from "../../types/CreateCallRequestOnNoHumanAnswer";

export const CreateCallRequest: core.serialization.Schema<serializers.CreateCallRequest.Raw, Vocode.CreateCallRequest> =
    core.serialization.object({
        fromNumber: core.serialization.property("from_number", core.serialization.string()),
        toNumber: core.serialization.property("to_number", core.serialization.string()),
        agent: CreateCallRequestAgent,
        onNoHumanAnswer: core.serialization.property("on_no_human_answer", CreateCallRequestOnNoHumanAnswer.optional()),
        runDoNotCallDetection: core.serialization.property(
            "run_do_not_call_detection",
            core.serialization.boolean().optional()
        ),
        hipaaCompliant: core.serialization.property("hipaa_compliant", core.serialization.boolean().optional()),
        context: core.serialization
            .record(core.serialization.string(), core.serialization.string().optional())
            .optional(),
        telephonyParams: core.serialization.property(
            "telephony_params",
            core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional()
        ),
    });

export declare namespace CreateCallRequest {
    interface Raw {
        from_number: string;
        to_number: string;
        agent: CreateCallRequestAgent.Raw;
        on_no_human_answer?: CreateCallRequestOnNoHumanAnswer.Raw | null;
        run_do_not_call_detection?: boolean | null;
        hipaa_compliant?: boolean | null;
        context?: Record<string, string | null | undefined> | null;
        telephony_params?: Record<string, string | null | undefined> | null;
    }
}
