/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             type: "action_add_to_conference"
 *         }
 *     }
 */
export interface UpdateActionRequest {
    id: string;
    body: Vocode.ActionUpdateParamsRequest;
}
