/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type AccountConnectionUpdateParamsRequest =
    | Vocode.OpenAiAccountConnectionUpdateParams
    | Vocode.TwilioAccountConnectionUpdateParams;
