/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type ActionResponseModel =
    | Vocode.AddToConferenceAction
    | Vocode.DtmfAction
    | Vocode.EndConversationAction
    | Vocode.ExternalAction
    | Vocode.SetHoldAction
    | Vocode.TransferCallAction;
