/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type ActionUpdateParamsRequest =
    | Vocode.AddToConferenceActionUpdateParams
    | Vocode.DtmfActionUpdateParams
    | Vocode.EndConversationActionUpdateParams
    | Vocode.ExternalActionUpdateParams
    | Vocode.SetHoldActionUpdateParams
    | Vocode.TransferCallActionUpdateParams;
