/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface AddToConferenceActionParams {
    type: "action_add_to_conference";
    config: Vocode.AddToConferenceConfig;
    actionTrigger?: Vocode.AddToConferenceActionParamsActionTrigger;
}
