/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type AddToConferenceActionParamsActionTrigger =
    | Vocode.FunctionCallActionTrigger
    | Vocode.PhraseBasedActionTriggerInput;
