/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type AgentUpdateParamsVoiceOne =
    | Vocode.AzureVoiceUpdateParams
    | Vocode.ElevenLabsVoiceUpdateParams
    | Vocode.PlayHtVoiceUpdateParams
    | Vocode.RimeVoiceUpdateParams
    | Vocode.VocodeVoiceUpdateParams;
