/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type AgentParamsActionsItemOne =
    | Vocode.AddToConferenceActionParams
    | Vocode.DtmfActionParams
    | Vocode.EndConversationActionParams
    | Vocode.ExternalActionParams
    | Vocode.SetHoldActionParams
    | Vocode.TransferCallActionParams;
