/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type AgentUpdateParamsVectorDatabase = string | Vocode.PineconeVectorDatabaseUpdateParams | Vocode.Undefined;
