/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface AzureVoiceUpdateParams {
    type: "voice_azure";
    voiceName?: Vocode.AzureVoiceUpdateParamsVoiceName;
    pitch?: Vocode.AzureVoiceUpdateParamsPitch;
    rate?: Vocode.AzureVoiceUpdateParamsRate;
}
