/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type CreateCallAgentParamsVoiceOne =
    | Vocode.AzureVoiceParams
    | Vocode.ElevenLabsVoiceParams
    | Vocode.PlayHtVoiceParams
    | Vocode.RimeVoiceParams
    | Vocode.VocodeVoiceParams;
