/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface DtmfActionUpdateParams {
    type: "action_dtmf";
    config?: Vocode.DtmfActionUpdateParamsConfig;
    actionTrigger?: Vocode.DtmfActionUpdateParamsActionTrigger;
}
