/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface ElevenLabsVoiceUpdateParams {
    type: "voice_eleven_labs";
    voiceId?: Vocode.ElevenLabsVoiceUpdateParamsVoiceId;
    stability?: Vocode.ElevenLabsVoiceUpdateParamsStability;
    similarityBoost?: Vocode.ElevenLabsVoiceUpdateParamsSimilarityBoost;
    apiKey?: Vocode.ElevenLabsVoiceUpdateParamsApiKey;
    optimizeStreamingLatency?: Vocode.ElevenLabsVoiceUpdateParamsOptimizeStreamingLatency;
    modelId?: Vocode.ElevenLabsVoiceUpdateParamsModelId;
    experimentalInputStreaming?: Vocode.ElevenLabsVoiceUpdateParamsExperimentalInputStreaming;
}
