/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type EndConversationActionUpdateParamsActionTrigger =
    | Vocode.EndConversationActionUpdateParamsActionTriggerZero
    | Vocode.Undefined;
