/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface EndConversationActionParams {
    type: "action_end_conversation";
    config?: Vocode.EmptyActionConfig;
    actionTrigger?: Vocode.EndConversationActionParamsActionTrigger;
}
