/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface EndConversationActionUpdateParams {
    type: "action_end_conversation";
    config?: Vocode.EndConversationActionUpdateParamsConfig;
    actionTrigger?: Vocode.EndConversationActionUpdateParamsActionTrigger;
}
