/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface ExternalAction {
    id: string;
    userId: string;
    type: "action_external";
    config: Vocode.ExternalActionConfig;
    actionTrigger?: Vocode.FunctionCallActionTrigger;
}
