/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface ExternalActionParams {
    type: "action_external";
    config: Vocode.ExternalActionConfig;
    actionTrigger?: Vocode.FunctionCallActionTrigger;
}
