/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface ExternalActionUpdateParams {
    type: "action_external";
    config?: Vocode.ExternalActionUpdateParamsConfig;
    actionTrigger?: Vocode.ExternalActionUpdateParamsActionTrigger;
}
