/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface FunctionCallActionTrigger {
    type: "action_trigger_function_call";
    config?: Vocode.FunctionCallActionTriggerConfig;
}
