/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InternalLlmFallbackProvider = "openai" | "azure";

export const InternalLlmFallbackProvider = {
    Openai: "openai",
    Azure: "azure",
} as const;
