/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface NormalizedCall {
    id: string;
    userId: string;
    status?: Vocode.CallStatus;
    errorMessage?: string;
    recordingAvailable?: boolean;
    transcript?: string;
    humanDetectionResult?: Vocode.NormalizedCallHumanDetectionResult;
    doNotCallResult?: boolean;
    telephonyId?: string;
    stage?: Vocode.NormalizedCallStage;
    stageOutcome?: Vocode.NormalizedCallStageOutcome;
    telephonyMetadata?: Vocode.NormalizedCallTelephonyMetadata;
    startTime?: number;
    endTime?: number;
    toNumber: string;
    fromNumber: string;
    agent: string;
    telephonyProvider: Vocode.NormalizedCallTelephonyProvider;
    agentPhoneNumber: string;
    hipaaCompliant?: boolean;
    onNoHumanAnswer?: Vocode.NormalizedCallOnNoHumanAnswer;
    context?: Record<string, string | undefined>;
    runDoNotCallDetection?: boolean;
    telephonyAccountConnection?: Vocode.NormalizedCallTelephonyAccountConnection;
    telephonyParams?: Record<string, string | undefined>;
}
