/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface NormalizedPhoneNumber {
    id: string;
    userId: string;
    active?: boolean;
    label?: string;
    inboundAgent?: string;
    outboundOnly?: boolean;
    exampleContext?: Record<string, string | undefined>;
    number: string;
    telephonyProvider?: Vocode.NormalizedPhoneNumberTelephonyProvider;
    telephonyAccountConnection?: Vocode.NormalizedPhoneNumberTelephonyAccountConnection;
}
