/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface OpenAiAccountConnectionUpdateParams {
    credentials?: Vocode.OpenAiAccountConnectionUpdateParamsCredentials;
    type: "account_connection_openai";
}
