/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface PhraseBasedActionTriggerInput {
    type: "action_trigger_phrase_based";
    config: Vocode.PhraseBasedActionTriggerConfig;
}
