/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface PlayHtVoiceParams {
    type: "voice_play_ht";
    voiceId: string;
    apiUserId?: string;
    apiKey?: string;
    version?: Vocode.PlayHtVoiceParamsVersion;
    speed?: number;
    quality?: Vocode.PlayHtVoiceParamsQuality;
    temperature?: number;
    topP?: number;
    textGuidance?: number;
    voiceGuidance?: number;
    experimentalRemoveSilence?: boolean;
}
