/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface RimeVoiceUpdateParams {
    type: "voice_rime";
    speaker?: Vocode.RimeVoiceUpdateParamsSpeaker;
    speedAlpha?: Vocode.RimeVoiceUpdateParamsSpeedAlpha;
    modelId?: Vocode.RimeVoiceUpdateParamsModelId;
}
