/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface RimeVoiceParams {
    type: "voice_rime";
    speaker: string;
    speedAlpha?: number;
    modelId?: Vocode.RimeVoiceParamsModelId;
}
