/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface RimeVoice {
    id: string;
    userId: string;
    type: "voice_rime";
    speaker: string;
    speedAlpha?: number;
    modelId?: Vocode.RimeVoiceModelId;
}
