/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface SetHoldAction {
    id: string;
    userId: string;
    type: "action_set_hold";
    config?: Vocode.EmptyActionConfig;
    actionTrigger?: Vocode.SetHoldActionActionTrigger;
}
