/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface SetHoldActionUpdateParams {
    type: "action_set_hold";
    config?: Vocode.SetHoldActionUpdateParamsConfig;
    actionTrigger?: Vocode.SetHoldActionUpdateParamsActionTrigger;
}
