/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface TransferCallActionParams {
    type: "action_transfer_call";
    config: Vocode.TransferCallConfig;
    actionTrigger?: Vocode.TransferCallActionParamsActionTrigger;
}
