/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface TransferCallActionUpdateParams {
    type: "action_transfer_call";
    config?: Vocode.TransferCallActionUpdateParamsConfig;
    actionTrigger?: Vocode.TransferCallActionUpdateParamsActionTrigger;
}
