/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface TransferCallAction {
    id: string;
    userId: string;
    type: "action_transfer_call";
    config: Vocode.TransferCallConfig;
    actionTrigger?: Vocode.TransferCallActionActionTrigger;
}
