/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TwilioTelephonyMetadata {
    type: "telephony_metadata_twilio";
    callSid?: string;
    callStatus?: string;
    transferCallSid?: string;
    transferCallStatus?: string;
    conferenceSid?: string;
}
