/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface TwilioAccountConnectionUpdateParams {
    credentials?: Vocode.TwilioAccountConnectionUpdateParamsCredentials;
    type: "account_connection_twilio";
}
