/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface VocodeVoiceUpdateParams {
    type: "voice_vocode";
    voiceId?: Vocode.VocodeVoiceUpdateParamsVoiceId;
}
