/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export type VoiceResponseModel =
    | Vocode.AzureVoice
    | Vocode.ElevenLabsVoice
    | Vocode.PlayHtVoice
    | Vocode.RimeVoice
    | Vocode.VocodeVoice;
