/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             type: "voice_azure"
 *         }
 *     }
 */
export interface UpdateVoiceRequest {
    id: string;
    body: Vocode.VoiceUpdateParamsRequest;
}
