/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {}
 */
export interface BuyPhoneNumberRequest {
    areaCode?: string;
    telephonyProvider?: Vocode.BuyPhoneNumberRequestTelephonyProvider;
    telephonyAccountConnection?: string;
    inboundAgent?: Vocode.BuyPhoneNumberRequestInboundAgent;
}
