/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         phoneNumber: "phone_number"
 *     }
 */
export interface GetNumberRequest {
    phoneNumber: string;
}
