/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {
 *         phoneNumber: "phone_number",
 *         telephonyAccountConnection: "telephony_account_connection"
 *     }
 */
export interface LinkPhoneNumberRequest {
    phoneNumber: string;
    telephonyAccountConnection: string;
    outboundOnly?: boolean;
    inboundAgent?: Vocode.LinkPhoneNumberRequestInboundAgent;
}
