/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { OpenAiAccountConnection } from "./OpenAiAccountConnection";
import { TwilioAccountConnection } from "./TwilioAccountConnection";

export const AccountConnectionPageItemsItem: core.serialization.Schema<
    serializers.AccountConnectionPageItemsItem.Raw,
    Vocode.AccountConnectionPageItemsItem
> = core.serialization.undiscriminatedUnion([OpenAiAccountConnection, TwilioAccountConnection]);

export declare namespace AccountConnectionPageItemsItem {
    type Raw = OpenAiAccountConnection.Raw | TwilioAccountConnection.Raw;
}
