/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { OpenAiAccountConnectionUpdateParams } from "./OpenAiAccountConnectionUpdateParams";
import { TwilioAccountConnectionUpdateParams } from "./TwilioAccountConnectionUpdateParams";

export const AccountConnectionUpdateParamsRequest: core.serialization.Schema<
    serializers.AccountConnectionUpdateParamsRequest.Raw,
    Vocode.AccountConnectionUpdateParamsRequest
> = core.serialization.undiscriminatedUnion([OpenAiAccountConnectionUpdateParams, TwilioAccountConnectionUpdateParams]);

export declare namespace AccountConnectionUpdateParamsRequest {
    type Raw = OpenAiAccountConnectionUpdateParams.Raw | TwilioAccountConnectionUpdateParams.Raw;
}
