/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const AddToSteeringPoolBody: core.serialization.ObjectSchema<
    serializers.AddToSteeringPoolBody.Raw,
    Vocode.AddToSteeringPoolBody
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optional()),
});

export declare namespace AddToSteeringPoolBody {
    interface Raw {
        phone_number?: string | null;
    }
}
