/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AddToConferenceConfig } from "./AddToConferenceConfig";
import { AddToConferenceActionParamsActionTrigger } from "./AddToConferenceActionParamsActionTrigger";

export const AddToConferenceActionParams: core.serialization.ObjectSchema<
    serializers.AddToConferenceActionParams.Raw,
    Vocode.AddToConferenceActionParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_add_to_conference"),
    config: AddToConferenceConfig,
    actionTrigger: core.serialization.property("action_trigger", AddToConferenceActionParamsActionTrigger.optional()),
});

export declare namespace AddToConferenceActionParams {
    interface Raw {
        type: "action_add_to_conference";
        config: AddToConferenceConfig.Raw;
        action_trigger?: AddToConferenceActionParamsActionTrigger.Raw | null;
    }
}
