/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AddToConferenceActionUpdateParamsConfig } from "./AddToConferenceActionUpdateParamsConfig";
import { AddToConferenceActionUpdateParamsActionTrigger } from "./AddToConferenceActionUpdateParamsActionTrigger";

export const AddToConferenceActionUpdateParams: core.serialization.ObjectSchema<
    serializers.AddToConferenceActionUpdateParams.Raw,
    Vocode.AddToConferenceActionUpdateParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_add_to_conference"),
    config: AddToConferenceActionUpdateParamsConfig.optional(),
    actionTrigger: core.serialization.property(
        "action_trigger",
        AddToConferenceActionUpdateParamsActionTrigger.optional()
    ),
});

export declare namespace AddToConferenceActionUpdateParams {
    interface Raw {
        type: "action_add_to_conference";
        config?: AddToConferenceActionUpdateParamsConfig.Raw | null;
        action_trigger?: AddToConferenceActionUpdateParamsActionTrigger.Raw | null;
    }
}
