/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { FunctionCallActionTrigger } from "./FunctionCallActionTrigger";
import { PhraseBasedActionTriggerInput } from "./PhraseBasedActionTriggerInput";

export const AddToConferenceActionUpdateParamsActionTriggerZero: core.serialization.Schema<
    serializers.AddToConferenceActionUpdateParamsActionTriggerZero.Raw,
    Vocode.AddToConferenceActionUpdateParamsActionTriggerZero
> = core.serialization.undiscriminatedUnion([FunctionCallActionTrigger, PhraseBasedActionTriggerInput]);

export declare namespace AddToConferenceActionUpdateParamsActionTriggerZero {
    type Raw = FunctionCallActionTrigger.Raw | PhraseBasedActionTriggerInput.Raw;
}
