/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AgentParamsVoiceOne } from "./AgentParamsVoiceOne";

export const AgentParamsVoice: core.serialization.Schema<serializers.AgentParamsVoice.Raw, Vocode.AgentParamsVoice> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), AgentParamsVoiceOne]);

export declare namespace AgentParamsVoice {
    type Raw = string | AgentParamsVoiceOne.Raw;
}
