/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Language } from "./Language";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsLanguage: core.serialization.Schema<
    serializers.AgentUpdateParamsLanguage.Raw,
    Vocode.AgentUpdateParamsLanguage
> = core.serialization.undiscriminatedUnion([Language, Undefined]);

export declare namespace AgentUpdateParamsLanguage {
    type Raw = Language.Raw | Undefined.Raw;
}
