/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const AgentDeepgramKeywordsValue: core.serialization.Schema<
    serializers.AgentDeepgramKeywordsValue.Raw,
    Vocode.AgentDeepgramKeywordsValue
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.number()]);

export declare namespace AgentDeepgramKeywordsValue {
    type Raw = number | number;
}
