/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { WebhookParams } from "./WebhookParams";

export const AgentParamsWebhook: core.serialization.Schema<
    serializers.AgentParamsWebhook.Raw,
    Vocode.AgentParamsWebhook
> = core.serialization.undiscriminatedUnion([core.serialization.string(), WebhookParams]);

export declare namespace AgentParamsWebhook {
    type Raw = string | WebhookParams.Raw;
}
