/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AgentUpdateParamsActionsItem } from "./AgentUpdateParamsActionsItem";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsActions: core.serialization.Schema<
    serializers.AgentUpdateParamsActions.Raw,
    Vocode.AgentUpdateParamsActions
> = core.serialization.undiscriminatedUnion([core.serialization.list(AgentUpdateParamsActionsItem), Undefined]);

export declare namespace AgentUpdateParamsActions {
    type Raw = AgentUpdateParamsActionsItem.Raw[] | Undefined.Raw;
}
