/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsOpenaiModelNameOverride: core.serialization.Schema<
    serializers.AgentUpdateParamsOpenaiModelNameOverride.Raw,
    Vocode.AgentUpdateParamsOpenaiModelNameOverride
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace AgentUpdateParamsOpenaiModelNameOverride {
    type Raw = string | Undefined.Raw;
}
