/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const AgentUpdateParamsDeepgramKeywordsZeroValue: core.serialization.Schema<
    serializers.AgentUpdateParamsDeepgramKeywordsZeroValue.Raw,
    Vocode.AgentUpdateParamsDeepgramKeywordsZeroValue
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.number()]);

export declare namespace AgentUpdateParamsDeepgramKeywordsZeroValue {
    type Raw = number | number;
}
