/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AgentParamsActionsItemOne } from "./AgentParamsActionsItemOne";

export const AgentParamsActionsItem: core.serialization.Schema<
    serializers.AgentParamsActionsItem.Raw,
    Vocode.AgentParamsActionsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), AgentParamsActionsItemOne]);

export declare namespace AgentParamsActionsItem {
    type Raw = string | AgentParamsActionsItemOne.Raw;
}
