/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsRunDoNotCallDetection: core.serialization.Schema<
    serializers.AgentUpdateParamsRunDoNotCallDetection.Raw,
    Vocode.AgentUpdateParamsRunDoNotCallDetection
> = core.serialization.undiscriminatedUnion([core.serialization.boolean(), Undefined]);

export declare namespace AgentUpdateParamsRunDoNotCallDetection {
    type Raw = boolean | Undefined.Raw;
}
