/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PineconeVectorDatabaseUpdateParams } from "./PineconeVectorDatabaseUpdateParams";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsVectorDatabase: core.serialization.Schema<
    serializers.AgentUpdateParamsVectorDatabase.Raw,
    Vocode.AgentUpdateParamsVectorDatabase
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    PineconeVectorDatabaseUpdateParams,
    Undefined,
]);

export declare namespace AgentUpdateParamsVectorDatabase {
    type Raw = string | PineconeVectorDatabaseUpdateParams.Raw | Undefined.Raw;
}
