/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const AgentEndpointingSensitivity: core.serialization.Schema<
    serializers.AgentEndpointingSensitivity.Raw,
    Vocode.AgentEndpointingSensitivity
> = core.serialization.enum_(["auto", "relaxed", "sensitive"]);

export declare namespace AgentEndpointingSensitivity {
    type Raw = "auto" | "relaxed" | "sensitive";
}
