/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsIvrNavigationMode: core.serialization.Schema<
    serializers.AgentUpdateParamsIvrNavigationMode.Raw,
    Vocode.AgentUpdateParamsIvrNavigationMode
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("default"),
    core.serialization.stringLiteral("off"),
    Undefined,
]);

export declare namespace AgentUpdateParamsIvrNavigationMode {
    type Raw = "default" | "off" | Undefined.Raw;
}
