/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AgentUpdateParamsActionsItemOne } from "./AgentUpdateParamsActionsItemOne";

export const AgentUpdateParamsActionsItem: core.serialization.Schema<
    serializers.AgentUpdateParamsActionsItem.Raw,
    Vocode.AgentUpdateParamsActionsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), AgentUpdateParamsActionsItemOne]);

export declare namespace AgentUpdateParamsActionsItem {
    type Raw = string | AgentUpdateParamsActionsItemOne.Raw;
}
