/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { OpenAiAccountConnection } from "./OpenAiAccountConnection";

export const AgentParamsOpenaiAccountConnection: core.serialization.Schema<
    serializers.AgentParamsOpenaiAccountConnection.Raw,
    Vocode.AgentParamsOpenaiAccountConnection
> = core.serialization.undiscriminatedUnion([OpenAiAccountConnection, core.serialization.string()]);

export declare namespace AgentParamsOpenaiAccountConnection {
    type Raw = OpenAiAccountConnection.Raw | string;
}
