/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PromptUpdateParams } from "./PromptUpdateParams";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsPrompt: core.serialization.Schema<
    serializers.AgentUpdateParamsPrompt.Raw,
    Vocode.AgentUpdateParamsPrompt
> = core.serialization.undiscriminatedUnion([core.serialization.string(), PromptUpdateParams, Undefined]);

export declare namespace AgentUpdateParamsPrompt {
    type Raw = string | PromptUpdateParams.Raw | Undefined.Raw;
}
