/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AddToConferenceActionUpdateParams } from "./AddToConferenceActionUpdateParams";
import { DtmfActionUpdateParams } from "./DtmfActionUpdateParams";
import { EndConversationActionUpdateParams } from "./EndConversationActionUpdateParams";
import { ExternalActionUpdateParams } from "./ExternalActionUpdateParams";
import { SetHoldActionUpdateParams } from "./SetHoldActionUpdateParams";
import { TransferCallActionUpdateParams } from "./TransferCallActionUpdateParams";

export const AgentUpdateParamsActionsItemOne: core.serialization.Schema<
    serializers.AgentUpdateParamsActionsItemOne.Raw,
    Vocode.AgentUpdateParamsActionsItemOne
> = core.serialization.undiscriminatedUnion([
    AddToConferenceActionUpdateParams,
    DtmfActionUpdateParams,
    EndConversationActionUpdateParams,
    ExternalActionUpdateParams,
    SetHoldActionUpdateParams,
    TransferCallActionUpdateParams,
]);

export declare namespace AgentUpdateParamsActionsItemOne {
    type Raw =
        | AddToConferenceActionUpdateParams.Raw
        | DtmfActionUpdateParams.Raw
        | EndConversationActionUpdateParams.Raw
        | ExternalActionUpdateParams.Raw
        | SetHoldActionUpdateParams.Raw
        | TransferCallActionUpdateParams.Raw;
}
