/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AgentUpdateParamsVoiceOne } from "./AgentUpdateParamsVoiceOne";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsVoice: core.serialization.Schema<
    serializers.AgentUpdateParamsVoice.Raw,
    Vocode.AgentUpdateParamsVoice
> = core.serialization.undiscriminatedUnion([core.serialization.string(), AgentUpdateParamsVoiceOne, Undefined]);

export declare namespace AgentUpdateParamsVoice {
    type Raw = string | AgentUpdateParamsVoiceOne.Raw | Undefined.Raw;
}
