/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PromptParams } from "./PromptParams";

export const AgentParamsPrompt: core.serialization.Schema<serializers.AgentParamsPrompt.Raw, Vocode.AgentParamsPrompt> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), PromptParams]);

export declare namespace AgentParamsPrompt {
    type Raw = string | PromptParams.Raw;
}
