/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsName: core.serialization.Schema<
    serializers.AgentUpdateParamsName.Raw,
    Vocode.AgentUpdateParamsName
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace AgentUpdateParamsName {
    type Raw = string | Undefined.Raw;
}
