/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const AgentParamsDeepgramKeywordsValue: core.serialization.Schema<
    serializers.AgentParamsDeepgramKeywordsValue.Raw,
    Vocode.AgentParamsDeepgramKeywordsValue
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.number()]);

export declare namespace AgentParamsDeepgramKeywordsValue {
    type Raw = number | number;
}
