/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { InternalLlmFallback } from "./InternalLlmFallback";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsLlmFallback: core.serialization.Schema<
    serializers.AgentUpdateParamsLlmFallback.Raw,
    Vocode.AgentUpdateParamsLlmFallback
> = core.serialization.undiscriminatedUnion([InternalLlmFallback, Undefined]);

export declare namespace AgentUpdateParamsLlmFallback {
    type Raw = InternalLlmFallback.Raw | Undefined.Raw;
}
