/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AgentUpdateParamsDeepgramKeywordsZeroValue } from "./AgentUpdateParamsDeepgramKeywordsZeroValue";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsDeepgramKeywords: core.serialization.Schema<
    serializers.AgentUpdateParamsDeepgramKeywords.Raw,
    Vocode.AgentUpdateParamsDeepgramKeywords
> = core.serialization.undiscriminatedUnion([
    core.serialization.record(core.serialization.string(), AgentUpdateParamsDeepgramKeywordsZeroValue),
    Undefined,
]);

export declare namespace AgentUpdateParamsDeepgramKeywords {
    type Raw = Record<string, AgentUpdateParamsDeepgramKeywordsZeroValue.Raw> | Undefined.Raw;
}
