/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsInitialMessage: core.serialization.Schema<
    serializers.AgentUpdateParamsInitialMessage.Raw,
    Vocode.AgentUpdateParamsInitialMessage
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace AgentUpdateParamsInitialMessage {
    type Raw = string | Undefined.Raw;
}
