/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AzureVoice } from "./AzureVoice";
import { ElevenLabsVoice } from "./ElevenLabsVoice";
import { PlayHtVoice } from "./PlayHtVoice";
import { RimeVoice } from "./RimeVoice";
import { VocodeVoice } from "./VocodeVoice";

export const AgentVoice: core.serialization.Schema<serializers.AgentVoice.Raw, Vocode.AgentVoice> =
    core.serialization.undiscriminatedUnion([AzureVoice, ElevenLabsVoice, PlayHtVoice, RimeVoice, VocodeVoice]);

export declare namespace AgentVoice {
    type Raw = AzureVoice.Raw | ElevenLabsVoice.Raw | PlayHtVoice.Raw | RimeVoice.Raw | VocodeVoice.Raw;
}
