/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsEndpointingSensitivity: core.serialization.Schema<
    serializers.AgentUpdateParamsEndpointingSensitivity.Raw,
    Vocode.AgentUpdateParamsEndpointingSensitivity
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("auto"),
    core.serialization.stringLiteral("relaxed"),
    core.serialization.stringLiteral("sensitive"),
    Undefined,
]);

export declare namespace AgentUpdateParamsEndpointingSensitivity {
    type Raw = "auto" | "relaxed" | "sensitive" | Undefined.Raw;
}
