/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const AgentParamsEndpointingSensitivity: core.serialization.Schema<
    serializers.AgentParamsEndpointingSensitivity.Raw,
    Vocode.AgentParamsEndpointingSensitivity
> = core.serialization.enum_(["auto", "relaxed", "sensitive"]);

export declare namespace AgentParamsEndpointingSensitivity {
    type Raw = "auto" | "relaxed" | "sensitive";
}
