/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AzureVoiceUpdateParamsVoiceName: core.serialization.Schema<
    serializers.AzureVoiceUpdateParamsVoiceName.Raw,
    Vocode.AzureVoiceUpdateParamsVoiceName
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace AzureVoiceUpdateParamsVoiceName {
    type Raw = string | Undefined.Raw;
}
