/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AzureVoiceUpdateParamsRate: core.serialization.Schema<
    serializers.AzureVoiceUpdateParamsRate.Raw,
    Vocode.AzureVoiceUpdateParamsRate
> = core.serialization.undiscriminatedUnion([core.serialization.number(), Undefined]);

export declare namespace AzureVoiceUpdateParamsRate {
    type Raw = number | Undefined.Raw;
}
