/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const CallStageOutcome: core.serialization.Schema<serializers.CallStageOutcome.Raw, Vocode.CallStageOutcome> =
    core.serialization.enum_([
        "human_unanswered",
        "call_did_not_connect",
        "human_disconnected",
        "bot_disconnected",
        "transfer_unanswered",
        "transfer_disconnected",
    ]);

export declare namespace CallStageOutcome {
    type Raw =
        | "human_unanswered"
        | "call_did_not_connect"
        | "human_disconnected"
        | "bot_disconnected"
        | "transfer_unanswered"
        | "transfer_disconnected";
}
