/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { NormalizedCall } from "./NormalizedCall";

export const CallPage: core.serialization.ObjectSchema<serializers.CallPage.Raw, Vocode.CallPage> =
    core.serialization.object({
        items: core.serialization.list(NormalizedCall),
        page: core.serialization.number(),
        size: core.serialization.number(),
        hasMore: core.serialization.property("has_more", core.serialization.boolean()),
        total: core.serialization.number(),
        totalIsEstimated: core.serialization.property("total_is_estimated", core.serialization.boolean()),
    });

export declare namespace CallPage {
    interface Raw {
        items: NormalizedCall.Raw[];
        page: number;
        size: number;
        has_more: boolean;
        total: number;
        total_is_estimated: boolean;
    }
}
