/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const CallStatus: core.serialization.Schema<serializers.CallStatus.Raw, Vocode.CallStatus> =
    core.serialization.enum_(["not_started", "in_progress", "error", "ended"]);

export declare namespace CallStatus {
    type Raw = "not_started" | "in_progress" | "error" | "ended";
}
