/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { CallStatus } from "./CallStatus";
import { CallHumanDetectionResult } from "./CallHumanDetectionResult";
import { CallStage } from "./CallStage";
import { CallStageOutcome } from "./CallStageOutcome";
import { CallTelephonyMetadata } from "./CallTelephonyMetadata";
import { Agent } from "./Agent";
import { CallTelephonyProvider } from "./CallTelephonyProvider";
import { CallOnNoHumanAnswer } from "./CallOnNoHumanAnswer";
import { TwilioAccountConnection } from "./TwilioAccountConnection";

export const Call: core.serialization.ObjectSchema<serializers.Call.Raw, Vocode.Call> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    status: CallStatus.optional(),
    errorMessage: core.serialization.property("error_message", core.serialization.string().optional()),
    recordingAvailable: core.serialization.property("recording_available", core.serialization.boolean().optional()),
    transcript: core.serialization.string().optional(),
    humanDetectionResult: core.serialization.property("human_detection_result", CallHumanDetectionResult.optional()),
    doNotCallResult: core.serialization.property("do_not_call_result", core.serialization.boolean().optional()),
    telephonyId: core.serialization.property("telephony_id", core.serialization.string().optional()),
    stage: CallStage.optional(),
    stageOutcome: core.serialization.property("stage_outcome", CallStageOutcome.optional()),
    telephonyMetadata: core.serialization.property("telephony_metadata", CallTelephonyMetadata.optional()),
    startTime: core.serialization.property("start_time", core.serialization.string().optional()),
    endTime: core.serialization.property("end_time", core.serialization.string().optional()),
    toNumber: core.serialization.property("to_number", core.serialization.string()),
    fromNumber: core.serialization.property("from_number", core.serialization.string()),
    agent: Agent,
    telephonyProvider: core.serialization.property("telephony_provider", CallTelephonyProvider),
    agentPhoneNumber: core.serialization.property("agent_phone_number", core.serialization.string()),
    hipaaCompliant: core.serialization.property("hipaa_compliant", core.serialization.boolean().optional()),
    onNoHumanAnswer: core.serialization.property("on_no_human_answer", CallOnNoHumanAnswer.optional()),
    context: core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional(),
    runDoNotCallDetection: core.serialization.property(
        "run_do_not_call_detection",
        core.serialization.boolean().optional()
    ),
    telephonyAccountConnection: core.serialization.property(
        "telephony_account_connection",
        TwilioAccountConnection.optional()
    ),
    telephonyParams: core.serialization.property(
        "telephony_params",
        core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional()
    ),
});

export declare namespace Call {
    interface Raw {
        id: string;
        user_id: string;
        status?: CallStatus.Raw | null;
        error_message?: string | null;
        recording_available?: boolean | null;
        transcript?: string | null;
        human_detection_result?: CallHumanDetectionResult.Raw | null;
        do_not_call_result?: boolean | null;
        telephony_id?: string | null;
        stage?: CallStage.Raw | null;
        stage_outcome?: CallStageOutcome.Raw | null;
        telephony_metadata?: CallTelephonyMetadata.Raw | null;
        start_time?: string | null;
        end_time?: string | null;
        to_number: string;
        from_number: string;
        agent: Agent.Raw;
        telephony_provider: CallTelephonyProvider.Raw;
        agent_phone_number: string;
        hipaa_compliant?: boolean | null;
        on_no_human_answer?: CallOnNoHumanAnswer.Raw | null;
        context?: Record<string, string | null | undefined> | null;
        run_do_not_call_detection?: boolean | null;
        telephony_account_connection?: TwilioAccountConnection.Raw | null;
        telephony_params?: Record<string, string | null | undefined> | null;
    }
}
