/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AddToConferenceActionParams } from "./AddToConferenceActionParams";
import { DtmfActionParams } from "./DtmfActionParams";
import { EndConversationActionParams } from "./EndConversationActionParams";
import { ExternalActionParams } from "./ExternalActionParams";
import { SetHoldActionParams } from "./SetHoldActionParams";
import { TransferCallActionParams } from "./TransferCallActionParams";

export const CreateCallAgentParamsActionsItemOne: core.serialization.Schema<
    serializers.CreateCallAgentParamsActionsItemOne.Raw,
    Vocode.CreateCallAgentParamsActionsItemOne
> = core.serialization.undiscriminatedUnion([
    AddToConferenceActionParams,
    DtmfActionParams,
    EndConversationActionParams,
    ExternalActionParams,
    SetHoldActionParams,
    TransferCallActionParams,
]);

export declare namespace CreateCallAgentParamsActionsItemOne {
    type Raw =
        | AddToConferenceActionParams.Raw
        | DtmfActionParams.Raw
        | EndConversationActionParams.Raw
        | ExternalActionParams.Raw
        | SetHoldActionParams.Raw
        | TransferCallActionParams.Raw;
}
