/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const CreateCallAgentParamsDeepgramKeywordsValue: core.serialization.Schema<
    serializers.CreateCallAgentParamsDeepgramKeywordsValue.Raw,
    Vocode.CreateCallAgentParamsDeepgramKeywordsValue
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.number()]);

export declare namespace CreateCallAgentParamsDeepgramKeywordsValue {
    type Raw = number | number;
}
