/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { CreateCallAgentParamsActionsItemOne } from "./CreateCallAgentParamsActionsItemOne";

export const CreateCallAgentParamsActionsItem: core.serialization.Schema<
    serializers.CreateCallAgentParamsActionsItem.Raw,
    Vocode.CreateCallAgentParamsActionsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), CreateCallAgentParamsActionsItemOne]);

export declare namespace CreateCallAgentParamsActionsItem {
    type Raw = string | CreateCallAgentParamsActionsItemOne.Raw;
}
