/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { WebhookParams } from "./WebhookParams";

export const CreateCallAgentParamsWebhook: core.serialization.Schema<
    serializers.CreateCallAgentParamsWebhook.Raw,
    Vocode.CreateCallAgentParamsWebhook
> = core.serialization.undiscriminatedUnion([core.serialization.string(), WebhookParams]);

export declare namespace CreateCallAgentParamsWebhook {
    type Raw = string | WebhookParams.Raw;
}
