/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PineconeVectorDatabaseParams } from "./PineconeVectorDatabaseParams";

export const CreateCallAgentParamsVectorDatabase: core.serialization.Schema<
    serializers.CreateCallAgentParamsVectorDatabase.Raw,
    Vocode.CreateCallAgentParamsVectorDatabase
> = core.serialization.undiscriminatedUnion([core.serialization.string(), PineconeVectorDatabaseParams]);

export declare namespace CreateCallAgentParamsVectorDatabase {
    type Raw = string | PineconeVectorDatabaseParams.Raw;
}
