/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const CreateCallAgentParamsEndpointingSensitivity: core.serialization.Schema<
    serializers.CreateCallAgentParamsEndpointingSensitivity.Raw,
    Vocode.CreateCallAgentParamsEndpointingSensitivity
> = core.serialization.enum_(["auto", "relaxed", "sensitive"]);

export declare namespace CreateCallAgentParamsEndpointingSensitivity {
    type Raw = "auto" | "relaxed" | "sensitive";
}
