/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { CreateCallAgentParamsVoiceOne } from "./CreateCallAgentParamsVoiceOne";

export const CreateCallAgentParamsVoice: core.serialization.Schema<
    serializers.CreateCallAgentParamsVoice.Raw,
    Vocode.CreateCallAgentParamsVoice
> = core.serialization.undiscriminatedUnion([core.serialization.string(), CreateCallAgentParamsVoiceOne]);

export declare namespace CreateCallAgentParamsVoice {
    type Raw = string | CreateCallAgentParamsVoiceOne.Raw;
}
