/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AzureVoiceParams } from "./AzureVoiceParams";
import { ElevenLabsVoiceParams } from "./ElevenLabsVoiceParams";
import { PlayHtVoiceParams } from "./PlayHtVoiceParams";
import { RimeVoiceParams } from "./RimeVoiceParams";
import { VocodeVoiceParams } from "./VocodeVoiceParams";

export const CreateCallAgentParamsVoiceOne: core.serialization.Schema<
    serializers.CreateCallAgentParamsVoiceOne.Raw,
    Vocode.CreateCallAgentParamsVoiceOne
> = core.serialization.undiscriminatedUnion([
    AzureVoiceParams,
    ElevenLabsVoiceParams,
    PlayHtVoiceParams,
    RimeVoiceParams,
    VocodeVoiceParams,
]);

export declare namespace CreateCallAgentParamsVoiceOne {
    type Raw =
        | AzureVoiceParams.Raw
        | ElevenLabsVoiceParams.Raw
        | PlayHtVoiceParams.Raw
        | RimeVoiceParams.Raw
        | VocodeVoiceParams.Raw;
}
