/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const CreateCallAgentParamsIvrNavigationMode: core.serialization.Schema<
    serializers.CreateCallAgentParamsIvrNavigationMode.Raw,
    Vocode.CreateCallAgentParamsIvrNavigationMode
> = core.serialization.enum_(["default", "off"]);

export declare namespace CreateCallAgentParamsIvrNavigationMode {
    type Raw = "default" | "off";
}
