/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { DtmfActionUpdateParamsConfig } from "./DtmfActionUpdateParamsConfig";
import { DtmfActionUpdateParamsActionTrigger } from "./DtmfActionUpdateParamsActionTrigger";

export const DtmfActionUpdateParams: core.serialization.ObjectSchema<
    serializers.DtmfActionUpdateParams.Raw,
    Vocode.DtmfActionUpdateParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_dtmf"),
    config: DtmfActionUpdateParamsConfig.optional(),
    actionTrigger: core.serialization.property("action_trigger", DtmfActionUpdateParamsActionTrigger.optional()),
});

export declare namespace DtmfActionUpdateParams {
    interface Raw {
        type: "action_dtmf";
        config?: DtmfActionUpdateParamsConfig.Raw | null;
        action_trigger?: DtmfActionUpdateParamsActionTrigger.Raw | null;
    }
}
