/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EmptyActionConfig } from "./EmptyActionConfig";
import { FunctionCallActionTrigger } from "./FunctionCallActionTrigger";

export const DtmfActionParams: core.serialization.ObjectSchema<
    serializers.DtmfActionParams.Raw,
    Vocode.DtmfActionParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_dtmf"),
    config: EmptyActionConfig.optional(),
    actionTrigger: core.serialization.property("action_trigger", FunctionCallActionTrigger.optional()),
});

export declare namespace DtmfActionParams {
    interface Raw {
        type: "action_dtmf";
        config?: EmptyActionConfig.Raw | null;
        action_trigger?: FunctionCallActionTrigger.Raw | null;
    }
}
