/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { FunctionCallActionTrigger } from "./FunctionCallActionTrigger";
import { Undefined } from "./Undefined";

export const DtmfActionUpdateParamsActionTrigger: core.serialization.Schema<
    serializers.DtmfActionUpdateParamsActionTrigger.Raw,
    Vocode.DtmfActionUpdateParamsActionTrigger
> = core.serialization.undiscriminatedUnion([FunctionCallActionTrigger, Undefined]);

export declare namespace DtmfActionUpdateParamsActionTrigger {
    type Raw = FunctionCallActionTrigger.Raw | Undefined.Raw;
}
