/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EmptyActionConfig } from "./EmptyActionConfig";
import { FunctionCallActionTrigger } from "./FunctionCallActionTrigger";

export const DtmfAction: core.serialization.ObjectSchema<serializers.DtmfAction.Raw, Vocode.DtmfAction> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        type: core.serialization.stringLiteral("action_dtmf"),
        config: EmptyActionConfig.optional(),
        actionTrigger: core.serialization.property("action_trigger", FunctionCallActionTrigger.optional()),
    });

export declare namespace DtmfAction {
    interface Raw {
        id: string;
        user_id: string;
        type: "action_dtmf";
        config?: EmptyActionConfig.Raw | null;
        action_trigger?: FunctionCallActionTrigger.Raw | null;
    }
}
