/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const ElevenLabsVoiceParams: core.serialization.ObjectSchema<
    serializers.ElevenLabsVoiceParams.Raw,
    Vocode.ElevenLabsVoiceParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("voice_eleven_labs"),
    voiceId: core.serialization.property("voice_id", core.serialization.string()),
    stability: core.serialization.number().optional(),
    similarityBoost: core.serialization.property("similarity_boost", core.serialization.number().optional()),
    apiKey: core.serialization.property("api_key", core.serialization.string().optional()),
    optimizeStreamingLatency: core.serialization.property(
        "optimize_streaming_latency",
        core.serialization.number().optional()
    ),
    modelId: core.serialization.property("model_id", core.serialization.string().optional()),
    experimentalInputStreaming: core.serialization.property(
        "experimental_input_streaming",
        core.serialization.boolean().optional()
    ),
});

export declare namespace ElevenLabsVoiceParams {
    interface Raw {
        type: "voice_eleven_labs";
        voice_id: string;
        stability?: number | null;
        similarity_boost?: number | null;
        api_key?: string | null;
        optimize_streaming_latency?: number | null;
        model_id?: string | null;
        experimental_input_streaming?: boolean | null;
    }
}
