/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const ElevenLabsVoiceUpdateParamsExperimentalInputStreaming: core.serialization.Schema<
    serializers.ElevenLabsVoiceUpdateParamsExperimentalInputStreaming.Raw,
    Vocode.ElevenLabsVoiceUpdateParamsExperimentalInputStreaming
> = core.serialization.undiscriminatedUnion([core.serialization.boolean(), Undefined]);

export declare namespace ElevenLabsVoiceUpdateParamsExperimentalInputStreaming {
    type Raw = boolean | Undefined.Raw;
}
