/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const ElevenLabsVoiceUpdateParamsModelId: core.serialization.Schema<
    serializers.ElevenLabsVoiceUpdateParamsModelId.Raw,
    Vocode.ElevenLabsVoiceUpdateParamsModelId
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace ElevenLabsVoiceUpdateParamsModelId {
    type Raw = string | Undefined.Raw;
}
