/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const ElevenLabsVoiceUpdateParamsSimilarityBoost: core.serialization.Schema<
    serializers.ElevenLabsVoiceUpdateParamsSimilarityBoost.Raw,
    Vocode.ElevenLabsVoiceUpdateParamsSimilarityBoost
> = core.serialization.undiscriminatedUnion([core.serialization.number(), Undefined]);

export declare namespace ElevenLabsVoiceUpdateParamsSimilarityBoost {
    type Raw = number | Undefined.Raw;
}
