/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const ElevenLabsVoiceUpdateParamsVoiceId: core.serialization.Schema<
    serializers.ElevenLabsVoiceUpdateParamsVoiceId.Raw,
    Vocode.ElevenLabsVoiceUpdateParamsVoiceId
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace ElevenLabsVoiceUpdateParamsVoiceId {
    type Raw = string | Undefined.Raw;
}
