/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EmptyActionConfig } from "./EmptyActionConfig";
import { EndConversationActionParamsActionTrigger } from "./EndConversationActionParamsActionTrigger";

export const EndConversationActionParams: core.serialization.ObjectSchema<
    serializers.EndConversationActionParams.Raw,
    Vocode.EndConversationActionParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_end_conversation"),
    config: EmptyActionConfig.optional(),
    actionTrigger: core.serialization.property("action_trigger", EndConversationActionParamsActionTrigger.optional()),
});

export declare namespace EndConversationActionParams {
    interface Raw {
        type: "action_end_conversation";
        config?: EmptyActionConfig.Raw | null;
        action_trigger?: EndConversationActionParamsActionTrigger.Raw | null;
    }
}
