/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EndConversationActionUpdateParamsConfig } from "./EndConversationActionUpdateParamsConfig";
import { EndConversationActionUpdateParamsActionTrigger } from "./EndConversationActionUpdateParamsActionTrigger";

export const EndConversationActionUpdateParams: core.serialization.ObjectSchema<
    serializers.EndConversationActionUpdateParams.Raw,
    Vocode.EndConversationActionUpdateParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_end_conversation"),
    config: EndConversationActionUpdateParamsConfig.optional(),
    actionTrigger: core.serialization.property(
        "action_trigger",
        EndConversationActionUpdateParamsActionTrigger.optional()
    ),
});

export declare namespace EndConversationActionUpdateParams {
    interface Raw {
        type: "action_end_conversation";
        config?: EndConversationActionUpdateParamsConfig.Raw | null;
        action_trigger?: EndConversationActionUpdateParamsActionTrigger.Raw | null;
    }
}
