/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EmptyActionConfig } from "./EmptyActionConfig";
import { EndConversationActionActionTrigger } from "./EndConversationActionActionTrigger";

export const EndConversationAction: core.serialization.ObjectSchema<
    serializers.EndConversationAction.Raw,
    Vocode.EndConversationAction
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    type: core.serialization.stringLiteral("action_end_conversation"),
    config: EmptyActionConfig.optional(),
    actionTrigger: core.serialization.property("action_trigger", EndConversationActionActionTrigger.optional()),
});

export declare namespace EndConversationAction {
    interface Raw {
        id: string;
        user_id: string;
        type: "action_end_conversation";
        config?: EmptyActionConfig.Raw | null;
        action_trigger?: EndConversationActionActionTrigger.Raw | null;
    }
}
