/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { ExternalActionConfig } from "./ExternalActionConfig";
import { FunctionCallActionTrigger } from "./FunctionCallActionTrigger";

export const ExternalAction: core.serialization.ObjectSchema<serializers.ExternalAction.Raw, Vocode.ExternalAction> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        type: core.serialization.stringLiteral("action_external"),
        config: ExternalActionConfig,
        actionTrigger: core.serialization.property("action_trigger", FunctionCallActionTrigger.optional()),
    });

export declare namespace ExternalAction {
    interface Raw {
        id: string;
        user_id: string;
        type: "action_external";
        config: ExternalActionConfig.Raw;
        action_trigger?: FunctionCallActionTrigger.Raw | null;
    }
}
