/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { ExternalActionConfig } from "./ExternalActionConfig";
import { FunctionCallActionTrigger } from "./FunctionCallActionTrigger";

export const ExternalActionParams: core.serialization.ObjectSchema<
    serializers.ExternalActionParams.Raw,
    Vocode.ExternalActionParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_external"),
    config: ExternalActionConfig,
    actionTrigger: core.serialization.property("action_trigger", FunctionCallActionTrigger.optional()),
});

export declare namespace ExternalActionParams {
    interface Raw {
        type: "action_external";
        config: ExternalActionConfig.Raw;
        action_trigger?: FunctionCallActionTrigger.Raw | null;
    }
}
