/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { ExternalActionConfig } from "./ExternalActionConfig";
import { Undefined } from "./Undefined";

export const ExternalActionUpdateParamsConfig: core.serialization.Schema<
    serializers.ExternalActionUpdateParamsConfig.Raw,
    Vocode.ExternalActionUpdateParamsConfig
> = core.serialization.undiscriminatedUnion([ExternalActionConfig, Undefined]);

export declare namespace ExternalActionUpdateParamsConfig {
    type Raw = ExternalActionConfig.Raw | Undefined.Raw;
}
