/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { ExternalActionUpdateParamsConfig } from "./ExternalActionUpdateParamsConfig";
import { ExternalActionUpdateParamsActionTrigger } from "./ExternalActionUpdateParamsActionTrigger";

export const ExternalActionUpdateParams: core.serialization.ObjectSchema<
    serializers.ExternalActionUpdateParams.Raw,
    Vocode.ExternalActionUpdateParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_external"),
    config: ExternalActionUpdateParamsConfig.optional(),
    actionTrigger: core.serialization.property("action_trigger", ExternalActionUpdateParamsActionTrigger.optional()),
});

export declare namespace ExternalActionUpdateParams {
    interface Raw {
        type: "action_external";
        config?: ExternalActionUpdateParamsConfig.Raw | null;
        action_trigger?: ExternalActionUpdateParamsActionTrigger.Raw | null;
    }
}
