/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { FunctionCallActionTriggerConfig } from "./FunctionCallActionTriggerConfig";

export const FunctionCallActionTrigger: core.serialization.ObjectSchema<
    serializers.FunctionCallActionTrigger.Raw,
    Vocode.FunctionCallActionTrigger
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_trigger_function_call"),
    config: FunctionCallActionTriggerConfig.optional(),
});

export declare namespace FunctionCallActionTrigger {
    interface Raw {
        type: "action_trigger_function_call";
        config?: FunctionCallActionTriggerConfig.Raw | null;
    }
}
