/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { InternalLlmFallbackProvider } from "./InternalLlmFallbackProvider";

export const InternalLlmFallback: core.serialization.ObjectSchema<
    serializers.InternalLlmFallback.Raw,
    Vocode.InternalLlmFallback
> = core.serialization.object({
    provider: InternalLlmFallbackProvider,
    modelName: core.serialization.property("model_name", core.serialization.string()),
});

export declare namespace InternalLlmFallback {
    interface Raw {
        provider: InternalLlmFallbackProvider.Raw;
        model_name: string;
    }
}
