/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const NormalizedCallTelephonyProvider: core.serialization.Schema<
    serializers.NormalizedCallTelephonyProvider.Raw,
    Vocode.NormalizedCallTelephonyProvider
> = core.serialization.enum_(["vonage", "twilio"]);

export declare namespace NormalizedCallTelephonyProvider {
    type Raw = "vonage" | "twilio";
}
