/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PineconeVectorDatabaseParams } from "./PineconeVectorDatabaseParams";

export const NormalizedAgentVectorDatabase: core.serialization.Schema<
    serializers.NormalizedAgentVectorDatabase.Raw,
    Vocode.NormalizedAgentVectorDatabase
> = core.serialization.undiscriminatedUnion([core.serialization.string(), PineconeVectorDatabaseParams]);

export declare namespace NormalizedAgentVectorDatabase {
    type Raw = string | PineconeVectorDatabaseParams.Raw;
}
