/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { OpenAiAccountConnection } from "./OpenAiAccountConnection";

export const NormalizedAgentOpenaiAccountConnection: core.serialization.Schema<
    serializers.NormalizedAgentOpenaiAccountConnection.Raw,
    Vocode.NormalizedAgentOpenaiAccountConnection
> = core.serialization.undiscriminatedUnion([OpenAiAccountConnection, core.serialization.string()]);

export declare namespace NormalizedAgentOpenaiAccountConnection {
    type Raw = OpenAiAccountConnection.Raw | string;
}
