/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { TwilioTelephonyMetadata } from "./TwilioTelephonyMetadata";
import { VonageTelephonyMetadata } from "./VonageTelephonyMetadata";

export const NormalizedCallTelephonyMetadata: core.serialization.Schema<
    serializers.NormalizedCallTelephonyMetadata.Raw,
    Vocode.NormalizedCallTelephonyMetadata
> = core.serialization.undiscriminatedUnion([TwilioTelephonyMetadata, VonageTelephonyMetadata]);

export declare namespace NormalizedCallTelephonyMetadata {
    type Raw = TwilioTelephonyMetadata.Raw | VonageTelephonyMetadata.Raw;
}
