/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { NormalizedPhoneNumberTelephonyProvider } from "./NormalizedPhoneNumberTelephonyProvider";
import { NormalizedPhoneNumberTelephonyAccountConnection } from "./NormalizedPhoneNumberTelephonyAccountConnection";

export const NormalizedPhoneNumber: core.serialization.ObjectSchema<
    serializers.NormalizedPhoneNumber.Raw,
    Vocode.NormalizedPhoneNumber
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    active: core.serialization.boolean().optional(),
    label: core.serialization.string().optional(),
    inboundAgent: core.serialization.property("inbound_agent", core.serialization.string().optional()),
    outboundOnly: core.serialization.property("outbound_only", core.serialization.boolean().optional()),
    exampleContext: core.serialization.property(
        "example_context",
        core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional()
    ),
    number: core.serialization.string(),
    telephonyProvider: core.serialization.property(
        "telephony_provider",
        NormalizedPhoneNumberTelephonyProvider.optional()
    ),
    telephonyAccountConnection: core.serialization.property(
        "telephony_account_connection",
        NormalizedPhoneNumberTelephonyAccountConnection.optional()
    ),
});

export declare namespace NormalizedPhoneNumber {
    interface Raw {
        id: string;
        user_id: string;
        active?: boolean | null;
        label?: string | null;
        inbound_agent?: string | null;
        outbound_only?: boolean | null;
        example_context?: Record<string, string | null | undefined> | null;
        number: string;
        telephony_provider?: NormalizedPhoneNumberTelephonyProvider.Raw | null;
        telephony_account_connection?: NormalizedPhoneNumberTelephonyAccountConnection.Raw | null;
    }
}
