/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const NormalizedAgentDeepgramKeywordsValue: core.serialization.Schema<
    serializers.NormalizedAgentDeepgramKeywordsValue.Raw,
    Vocode.NormalizedAgentDeepgramKeywordsValue
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.number()]);

export declare namespace NormalizedAgentDeepgramKeywordsValue {
    type Raw = number | number;
}
