/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { OpenAiAccountConnectionUpdateParamsCredentials } from "./OpenAiAccountConnectionUpdateParamsCredentials";

export const OpenAiAccountConnectionUpdateParams: core.serialization.ObjectSchema<
    serializers.OpenAiAccountConnectionUpdateParams.Raw,
    Vocode.OpenAiAccountConnectionUpdateParams
> = core.serialization.object({
    credentials: OpenAiAccountConnectionUpdateParamsCredentials.optional(),
    type: core.serialization.stringLiteral("account_connection_openai"),
});

export declare namespace OpenAiAccountConnectionUpdateParams {
    interface Raw {
        credentials?: OpenAiAccountConnectionUpdateParamsCredentials.Raw | null;
        type: "account_connection_openai";
    }
}
