/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { OpenAiCredentials } from "./OpenAiCredentials";

export const OpenAiAccountConnectionParams: core.serialization.ObjectSchema<
    serializers.OpenAiAccountConnectionParams.Raw,
    Vocode.OpenAiAccountConnectionParams
> = core.serialization.object({
    credentials: OpenAiCredentials,
    type: core.serialization.stringLiteral("account_connection_openai"),
});

export declare namespace OpenAiAccountConnectionParams {
    interface Raw {
        credentials: OpenAiCredentials.Raw;
        type: "account_connection_openai";
    }
}
