/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { OpenAiCredentials } from "./OpenAiCredentials";
import { Undefined } from "./Undefined";

export const OpenAiAccountConnectionUpdateParamsCredentials: core.serialization.Schema<
    serializers.OpenAiAccountConnectionUpdateParamsCredentials.Raw,
    Vocode.OpenAiAccountConnectionUpdateParamsCredentials
> = core.serialization.undiscriminatedUnion([OpenAiCredentials, Undefined]);

export declare namespace OpenAiAccountConnectionUpdateParamsCredentials {
    type Raw = OpenAiCredentials.Raw | Undefined.Raw;
}
