/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Agent } from "./Agent";
import { PhoneNumberTelephonyProvider } from "./PhoneNumberTelephonyProvider";
import { TwilioAccountConnection } from "./TwilioAccountConnection";

export const PhoneNumber: core.serialization.ObjectSchema<serializers.PhoneNumber.Raw, Vocode.PhoneNumber> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        active: core.serialization.boolean().optional(),
        label: core.serialization.string().optional(),
        inboundAgent: core.serialization.property("inbound_agent", Agent.optional()),
        outboundOnly: core.serialization.property("outbound_only", core.serialization.boolean().optional()),
        exampleContext: core.serialization.property(
            "example_context",
            core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional()
        ),
        number: core.serialization.string(),
        telephonyProvider: core.serialization.property("telephony_provider", PhoneNumberTelephonyProvider.optional()),
        telephonyAccountConnection: core.serialization.property(
            "telephony_account_connection",
            TwilioAccountConnection.optional()
        ),
    });

export declare namespace PhoneNumber {
    interface Raw {
        id: string;
        user_id: string;
        active?: boolean | null;
        label?: string | null;
        inbound_agent?: Agent.Raw | null;
        outbound_only?: boolean | null;
        example_context?: Record<string, string | null | undefined> | null;
        number: string;
        telephony_provider?: PhoneNumberTelephonyProvider.Raw | null;
        telephony_account_connection?: TwilioAccountConnection.Raw | null;
    }
}
