/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PhraseTrigger } from "./PhraseTrigger";

export const PhraseBasedActionTriggerConfig: core.serialization.ObjectSchema<
    serializers.PhraseBasedActionTriggerConfig.Raw,
    Vocode.PhraseBasedActionTriggerConfig
> = core.serialization.object({
    phraseTriggers: core.serialization.property("phrase_triggers", core.serialization.list(PhraseTrigger)),
});

export declare namespace PhraseBasedActionTriggerConfig {
    interface Raw {
        phrase_triggers: PhraseTrigger.Raw[];
    }
}
