/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PhraseBasedActionTriggerConfig } from "./PhraseBasedActionTriggerConfig";

export const PhraseBasedActionTriggerInput: core.serialization.ObjectSchema<
    serializers.PhraseBasedActionTriggerInput.Raw,
    Vocode.PhraseBasedActionTriggerInput
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_trigger_phrase_based"),
    config: PhraseBasedActionTriggerConfig,
});

export declare namespace PhraseBasedActionTriggerInput {
    interface Raw {
        type: "action_trigger_phrase_based";
        config: PhraseBasedActionTriggerConfig.Raw;
    }
}
