/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PineconeVectorDatabaseUpdateParamsIndex } from "./PineconeVectorDatabaseUpdateParamsIndex";
import { PineconeVectorDatabaseUpdateParamsApiKey } from "./PineconeVectorDatabaseUpdateParamsApiKey";
import { PineconeVectorDatabaseUpdateParamsApiEnvironment } from "./PineconeVectorDatabaseUpdateParamsApiEnvironment";

export const PineconeVectorDatabaseUpdateParams: core.serialization.ObjectSchema<
    serializers.PineconeVectorDatabaseUpdateParams.Raw,
    Vocode.PineconeVectorDatabaseUpdateParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("vector_database_pinecone"),
    index: PineconeVectorDatabaseUpdateParamsIndex.optional(),
    apiKey: core.serialization.property("api_key", PineconeVectorDatabaseUpdateParamsApiKey.optional()),
    apiEnvironment: core.serialization.property(
        "api_environment",
        PineconeVectorDatabaseUpdateParamsApiEnvironment.optional()
    ),
});

export declare namespace PineconeVectorDatabaseUpdateParams {
    interface Raw {
        type: "vector_database_pinecone";
        index?: PineconeVectorDatabaseUpdateParamsIndex.Raw | null;
        api_key?: PineconeVectorDatabaseUpdateParamsApiKey.Raw | null;
        api_environment?: PineconeVectorDatabaseUpdateParamsApiEnvironment.Raw | null;
    }
}
