/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PineconeVectorDatabaseUpdateParamsApiKey: core.serialization.Schema<
    serializers.PineconeVectorDatabaseUpdateParamsApiKey.Raw,
    Vocode.PineconeVectorDatabaseUpdateParamsApiKey
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace PineconeVectorDatabaseUpdateParamsApiKey {
    type Raw = string | Undefined.Raw;
}
