/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PineconeVectorDatabaseUpdateParamsApiEnvironment: core.serialization.Schema<
    serializers.PineconeVectorDatabaseUpdateParamsApiEnvironment.Raw,
    Vocode.PineconeVectorDatabaseUpdateParamsApiEnvironment
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace PineconeVectorDatabaseUpdateParamsApiEnvironment {
    type Raw = string | Undefined.Raw;
}
