/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsVoiceGuidance: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsVoiceGuidance.Raw,
    Vocode.PlayHtVoiceUpdateParamsVoiceGuidance
> = core.serialization.undiscriminatedUnion([core.serialization.number(), Undefined]);

export declare namespace PlayHtVoiceUpdateParamsVoiceGuidance {
    type Raw = number | Undefined.Raw;
}
