/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsQuality: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsQuality.Raw,
    Vocode.PlayHtVoiceUpdateParamsQuality
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("faster"),
    core.serialization.stringLiteral("draft"),
    core.serialization.stringLiteral("low"),
    core.serialization.stringLiteral("medium"),
    core.serialization.stringLiteral("high"),
    core.serialization.stringLiteral("premium"),
    Undefined,
]);

export declare namespace PlayHtVoiceUpdateParamsQuality {
    type Raw = "faster" | "draft" | "low" | "medium" | "high" | "premium" | Undefined.Raw;
}
