/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsVersion: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsVersion.Raw,
    Vocode.PlayHtVoiceUpdateParamsVersion
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("1"),
    core.serialization.stringLiteral("2"),
    Undefined,
]);

export declare namespace PlayHtVoiceUpdateParamsVersion {
    type Raw = "1" | "2" | Undefined.Raw;
}
