/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsTextGuidance: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsTextGuidance.Raw,
    Vocode.PlayHtVoiceUpdateParamsTextGuidance
> = core.serialization.undiscriminatedUnion([core.serialization.number(), Undefined]);

export declare namespace PlayHtVoiceUpdateParamsTextGuidance {
    type Raw = number | Undefined.Raw;
}
