/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsTemperature: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsTemperature.Raw,
    Vocode.PlayHtVoiceUpdateParamsTemperature
> = core.serialization.undiscriminatedUnion([core.serialization.number(), Undefined]);

export declare namespace PlayHtVoiceUpdateParamsTemperature {
    type Raw = number | Undefined.Raw;
}
