/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsApiUserId: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsApiUserId.Raw,
    Vocode.PlayHtVoiceUpdateParamsApiUserId
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace PlayHtVoiceUpdateParamsApiUserId {
    type Raw = string | Undefined.Raw;
}
