/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PlayHtVoiceUpdateParamsVoiceId } from "./PlayHtVoiceUpdateParamsVoiceId";
import { PlayHtVoiceUpdateParamsApiUserId } from "./PlayHtVoiceUpdateParamsApiUserId";
import { PlayHtVoiceUpdateParamsApiKey } from "./PlayHtVoiceUpdateParamsApiKey";
import { PlayHtVoiceUpdateParamsVersion } from "./PlayHtVoiceUpdateParamsVersion";
import { PlayHtVoiceUpdateParamsSpeed } from "./PlayHtVoiceUpdateParamsSpeed";
import { PlayHtVoiceUpdateParamsQuality } from "./PlayHtVoiceUpdateParamsQuality";
import { PlayHtVoiceUpdateParamsTemperature } from "./PlayHtVoiceUpdateParamsTemperature";
import { PlayHtVoiceUpdateParamsTopP } from "./PlayHtVoiceUpdateParamsTopP";
import { PlayHtVoiceUpdateParamsTextGuidance } from "./PlayHtVoiceUpdateParamsTextGuidance";
import { PlayHtVoiceUpdateParamsVoiceGuidance } from "./PlayHtVoiceUpdateParamsVoiceGuidance";
import { PlayHtVoiceUpdateParamsExperimentalRemoveSilence } from "./PlayHtVoiceUpdateParamsExperimentalRemoveSilence";

export const PlayHtVoiceUpdateParams: core.serialization.ObjectSchema<
    serializers.PlayHtVoiceUpdateParams.Raw,
    Vocode.PlayHtVoiceUpdateParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("voice_play_ht"),
    voiceId: core.serialization.property("voice_id", PlayHtVoiceUpdateParamsVoiceId.optional()),
    apiUserId: core.serialization.property("api_user_id", PlayHtVoiceUpdateParamsApiUserId.optional()),
    apiKey: core.serialization.property("api_key", PlayHtVoiceUpdateParamsApiKey.optional()),
    version: PlayHtVoiceUpdateParamsVersion.optional(),
    speed: PlayHtVoiceUpdateParamsSpeed.optional(),
    quality: PlayHtVoiceUpdateParamsQuality.optional(),
    temperature: PlayHtVoiceUpdateParamsTemperature.optional(),
    topP: core.serialization.property("top_p", PlayHtVoiceUpdateParamsTopP.optional()),
    textGuidance: core.serialization.property("text_guidance", PlayHtVoiceUpdateParamsTextGuidance.optional()),
    voiceGuidance: core.serialization.property("voice_guidance", PlayHtVoiceUpdateParamsVoiceGuidance.optional()),
    experimentalRemoveSilence: core.serialization.property(
        "experimental_remove_silence",
        PlayHtVoiceUpdateParamsExperimentalRemoveSilence.optional()
    ),
});

export declare namespace PlayHtVoiceUpdateParams {
    interface Raw {
        type: "voice_play_ht";
        voice_id?: PlayHtVoiceUpdateParamsVoiceId.Raw | null;
        api_user_id?: PlayHtVoiceUpdateParamsApiUserId.Raw | null;
        api_key?: PlayHtVoiceUpdateParamsApiKey.Raw | null;
        version?: PlayHtVoiceUpdateParamsVersion.Raw | null;
        speed?: PlayHtVoiceUpdateParamsSpeed.Raw | null;
        quality?: PlayHtVoiceUpdateParamsQuality.Raw | null;
        temperature?: PlayHtVoiceUpdateParamsTemperature.Raw | null;
        top_p?: PlayHtVoiceUpdateParamsTopP.Raw | null;
        text_guidance?: PlayHtVoiceUpdateParamsTextGuidance.Raw | null;
        voice_guidance?: PlayHtVoiceUpdateParamsVoiceGuidance.Raw | null;
        experimental_remove_silence?: PlayHtVoiceUpdateParamsExperimentalRemoveSilence.Raw | null;
    }
}
