/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PlayHtVoiceVersion } from "./PlayHtVoiceVersion";
import { PlayHtVoiceQuality } from "./PlayHtVoiceQuality";

export const PlayHtVoice: core.serialization.ObjectSchema<serializers.PlayHtVoice.Raw, Vocode.PlayHtVoice> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        type: core.serialization.stringLiteral("voice_play_ht"),
        voiceId: core.serialization.property("voice_id", core.serialization.string()),
        apiUserId: core.serialization.property("api_user_id", core.serialization.string().optional()),
        apiKey: core.serialization.property("api_key", core.serialization.string().optional()),
        version: PlayHtVoiceVersion.optional(),
        speed: core.serialization.number().optional(),
        quality: PlayHtVoiceQuality.optional(),
        temperature: core.serialization.number().optional(),
        topP: core.serialization.property("top_p", core.serialization.number().optional()),
        textGuidance: core.serialization.property("text_guidance", core.serialization.number().optional()),
        voiceGuidance: core.serialization.property("voice_guidance", core.serialization.number().optional()),
        experimentalRemoveSilence: core.serialization.property(
            "experimental_remove_silence",
            core.serialization.boolean().optional()
        ),
    });

export declare namespace PlayHtVoice {
    interface Raw {
        id: string;
        user_id: string;
        type: "voice_play_ht";
        voice_id: string;
        api_user_id?: string | null;
        api_key?: string | null;
        version?: PlayHtVoiceVersion.Raw | null;
        speed?: number | null;
        quality?: PlayHtVoiceQuality.Raw | null;
        temperature?: number | null;
        top_p?: number | null;
        text_guidance?: number | null;
        voice_guidance?: number | null;
        experimental_remove_silence?: boolean | null;
    }
}
