/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsExperimentalRemoveSilence: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsExperimentalRemoveSilence.Raw,
    Vocode.PlayHtVoiceUpdateParamsExperimentalRemoveSilence
> = core.serialization.undiscriminatedUnion([core.serialization.boolean(), Undefined]);

export declare namespace PlayHtVoiceUpdateParamsExperimentalRemoveSilence {
    type Raw = boolean | Undefined.Raw;
}
