/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsSpeed: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsSpeed.Raw,
    Vocode.PlayHtVoiceUpdateParamsSpeed
> = core.serialization.undiscriminatedUnion([core.serialization.number(), Undefined]);

export declare namespace PlayHtVoiceUpdateParamsSpeed {
    type Raw = number | Undefined.Raw;
}
