/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PlayHtVoiceParamsVersion } from "./PlayHtVoiceParamsVersion";
import { PlayHtVoiceParamsQuality } from "./PlayHtVoiceParamsQuality";

export const PlayHtVoiceParams: core.serialization.ObjectSchema<
    serializers.PlayHtVoiceParams.Raw,
    Vocode.PlayHtVoiceParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("voice_play_ht"),
    voiceId: core.serialization.property("voice_id", core.serialization.string()),
    apiUserId: core.serialization.property("api_user_id", core.serialization.string().optional()),
    apiKey: core.serialization.property("api_key", core.serialization.string().optional()),
    version: PlayHtVoiceParamsVersion.optional(),
    speed: core.serialization.number().optional(),
    quality: PlayHtVoiceParamsQuality.optional(),
    temperature: core.serialization.number().optional(),
    topP: core.serialization.property("top_p", core.serialization.number().optional()),
    textGuidance: core.serialization.property("text_guidance", core.serialization.number().optional()),
    voiceGuidance: core.serialization.property("voice_guidance", core.serialization.number().optional()),
    experimentalRemoveSilence: core.serialization.property(
        "experimental_remove_silence",
        core.serialization.boolean().optional()
    ),
});

export declare namespace PlayHtVoiceParams {
    interface Raw {
        type: "voice_play_ht";
        voice_id: string;
        api_user_id?: string | null;
        api_key?: string | null;
        version?: PlayHtVoiceParamsVersion.Raw | null;
        speed?: number | null;
        quality?: PlayHtVoiceParamsQuality.Raw | null;
        temperature?: number | null;
        top_p?: number | null;
        text_guidance?: number | null;
        voice_guidance?: number | null;
        experimental_remove_silence?: boolean | null;
    }
}
