/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PlayHtVoiceUpdateParamsVoiceId: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsVoiceId.Raw,
    Vocode.PlayHtVoiceUpdateParamsVoiceId
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace PlayHtVoiceUpdateParamsVoiceId {
    type Raw = string | Undefined.Raw;
}
