/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const PromptUpdateParamsContextEndpoint: core.serialization.Schema<
    serializers.PromptUpdateParamsContextEndpoint.Raw,
    Vocode.PromptUpdateParamsContextEndpoint
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace PromptUpdateParamsContextEndpoint {
    type Raw = string | Undefined.Raw;
}
