/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PromptUpdateParamsContent } from "./PromptUpdateParamsContent";
import { PromptUpdateParamsCollectFields } from "./PromptUpdateParamsCollectFields";
import { PromptUpdateParamsContextEndpoint } from "./PromptUpdateParamsContextEndpoint";
import { PromptUpdateParamsPromptTemplate } from "./PromptUpdateParamsPromptTemplate";

export const PromptUpdateParams: core.serialization.ObjectSchema<
    serializers.PromptUpdateParams.Raw,
    Vocode.PromptUpdateParams
> = core.serialization.object({
    content: PromptUpdateParamsContent.optional(),
    collectFields: core.serialization.property("collect_fields", PromptUpdateParamsCollectFields.optional()),
    contextEndpoint: core.serialization.property("context_endpoint", PromptUpdateParamsContextEndpoint.optional()),
    promptTemplate: core.serialization.property("prompt_template", PromptUpdateParamsPromptTemplate.optional()),
});

export declare namespace PromptUpdateParams {
    interface Raw {
        content?: PromptUpdateParamsContent.Raw | null;
        collect_fields?: PromptUpdateParamsCollectFields.Raw | null;
        context_endpoint?: PromptUpdateParamsContextEndpoint.Raw | null;
        prompt_template?: PromptUpdateParamsPromptTemplate.Raw | null;
    }
}
