/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PromptTemplate } from "./PromptTemplate";

export const PromptParamsPromptTemplate: core.serialization.Schema<
    serializers.PromptParamsPromptTemplate.Raw,
    Vocode.PromptParamsPromptTemplate
> = core.serialization.undiscriminatedUnion([core.serialization.string(), PromptTemplate]);

export declare namespace PromptParamsPromptTemplate {
    type Raw = string | PromptTemplate.Raw;
}
