/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PromptTemplate } from "./PromptTemplate";
import { Undefined } from "./Undefined";

export const PromptUpdateParamsPromptTemplate: core.serialization.Schema<
    serializers.PromptUpdateParamsPromptTemplate.Raw,
    Vocode.PromptUpdateParamsPromptTemplate
> = core.serialization.undiscriminatedUnion([core.serialization.string(), PromptTemplate, Undefined]);

export declare namespace PromptUpdateParamsPromptTemplate {
    type Raw = string | PromptTemplate.Raw | Undefined.Raw;
}
