/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { RimeVoiceModelId } from "./RimeVoiceModelId";

export const RimeVoice: core.serialization.ObjectSchema<serializers.RimeVoice.Raw, Vocode.RimeVoice> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        type: core.serialization.stringLiteral("voice_rime"),
        speaker: core.serialization.string(),
        speedAlpha: core.serialization.property("speed_alpha", core.serialization.number().optional()),
        modelId: core.serialization.property("model_id", RimeVoiceModelId.optional()),
    });

export declare namespace RimeVoice {
    interface Raw {
        id: string;
        user_id: string;
        type: "voice_rime";
        speaker: string;
        speed_alpha?: number | null;
        model_id?: RimeVoiceModelId.Raw | null;
    }
}
