/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { RimeVoiceParamsModelId } from "./RimeVoiceParamsModelId";

export const RimeVoiceParams: core.serialization.ObjectSchema<serializers.RimeVoiceParams.Raw, Vocode.RimeVoiceParams> =
    core.serialization.object({
        type: core.serialization.stringLiteral("voice_rime"),
        speaker: core.serialization.string(),
        speedAlpha: core.serialization.property("speed_alpha", core.serialization.number().optional()),
        modelId: core.serialization.property("model_id", RimeVoiceParamsModelId.optional()),
    });

export declare namespace RimeVoiceParams {
    interface Raw {
        type: "voice_rime";
        speaker: string;
        speed_alpha?: number | null;
        model_id?: RimeVoiceParamsModelId.Raw | null;
    }
}
