/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { FunctionCallActionTrigger } from "./FunctionCallActionTrigger";
import { PhraseBasedActionTriggerOutput } from "./PhraseBasedActionTriggerOutput";

export const SetHoldActionActionTrigger: core.serialization.Schema<
    serializers.SetHoldActionActionTrigger.Raw,
    Vocode.SetHoldActionActionTrigger
> = core.serialization.undiscriminatedUnion([FunctionCallActionTrigger, PhraseBasedActionTriggerOutput]);

export declare namespace SetHoldActionActionTrigger {
    type Raw = FunctionCallActionTrigger.Raw | PhraseBasedActionTriggerOutput.Raw;
}
