/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EmptyActionConfig } from "./EmptyActionConfig";
import { SetHoldActionActionTrigger } from "./SetHoldActionActionTrigger";

export const SetHoldAction: core.serialization.ObjectSchema<serializers.SetHoldAction.Raw, Vocode.SetHoldAction> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        type: core.serialization.stringLiteral("action_set_hold"),
        config: EmptyActionConfig.optional(),
        actionTrigger: core.serialization.property("action_trigger", SetHoldActionActionTrigger.optional()),
    });

export declare namespace SetHoldAction {
    interface Raw {
        id: string;
        user_id: string;
        type: "action_set_hold";
        config?: EmptyActionConfig.Raw | null;
        action_trigger?: SetHoldActionActionTrigger.Raw | null;
    }
}
