/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EmptyActionConfig } from "./EmptyActionConfig";
import { SetHoldActionParamsActionTrigger } from "./SetHoldActionParamsActionTrigger";

export const SetHoldActionParams: core.serialization.ObjectSchema<
    serializers.SetHoldActionParams.Raw,
    Vocode.SetHoldActionParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_set_hold"),
    config: EmptyActionConfig.optional(),
    actionTrigger: core.serialization.property("action_trigger", SetHoldActionParamsActionTrigger.optional()),
});

export declare namespace SetHoldActionParams {
    interface Raw {
        type: "action_set_hold";
        config?: EmptyActionConfig.Raw | null;
        action_trigger?: SetHoldActionParamsActionTrigger.Raw | null;
    }
}
