/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { SetHoldActionUpdateParamsActionTriggerZero } from "./SetHoldActionUpdateParamsActionTriggerZero";
import { Undefined } from "./Undefined";

export const SetHoldActionUpdateParamsActionTrigger: core.serialization.Schema<
    serializers.SetHoldActionUpdateParamsActionTrigger.Raw,
    Vocode.SetHoldActionUpdateParamsActionTrigger
> = core.serialization.undiscriminatedUnion([SetHoldActionUpdateParamsActionTriggerZero, Undefined]);

export declare namespace SetHoldActionUpdateParamsActionTrigger {
    type Raw = SetHoldActionUpdateParamsActionTriggerZero.Raw | Undefined.Raw;
}
