/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EmptyActionConfig } from "./EmptyActionConfig";
import { Undefined } from "./Undefined";

export const SetHoldActionUpdateParamsConfig: core.serialization.Schema<
    serializers.SetHoldActionUpdateParamsConfig.Raw,
    Vocode.SetHoldActionUpdateParamsConfig
> = core.serialization.undiscriminatedUnion([EmptyActionConfig, Undefined]);

export declare namespace SetHoldActionUpdateParamsConfig {
    type Raw = EmptyActionConfig.Raw | Undefined.Raw;
}
