/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { SetHoldActionUpdateParamsConfig } from "./SetHoldActionUpdateParamsConfig";
import { SetHoldActionUpdateParamsActionTrigger } from "./SetHoldActionUpdateParamsActionTrigger";

export const SetHoldActionUpdateParams: core.serialization.ObjectSchema<
    serializers.SetHoldActionUpdateParams.Raw,
    Vocode.SetHoldActionUpdateParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_set_hold"),
    config: SetHoldActionUpdateParamsConfig.optional(),
    actionTrigger: core.serialization.property("action_trigger", SetHoldActionUpdateParamsActionTrigger.optional()),
});

export declare namespace SetHoldActionUpdateParams {
    interface Raw {
        type: "action_set_hold";
        config?: SetHoldActionUpdateParamsConfig.Raw | null;
        action_trigger?: SetHoldActionUpdateParamsActionTrigger.Raw | null;
    }
}
