/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { TransferCallConfig } from "./TransferCallConfig";
import { Undefined } from "./Undefined";

export const TransferCallActionUpdateParamsConfig: core.serialization.Schema<
    serializers.TransferCallActionUpdateParamsConfig.Raw,
    Vocode.TransferCallActionUpdateParamsConfig
> = core.serialization.undiscriminatedUnion([TransferCallConfig, Undefined]);

export declare namespace TransferCallActionUpdateParamsConfig {
    type Raw = TransferCallConfig.Raw | Undefined.Raw;
}
