/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { TransferCallActionUpdateParamsActionTriggerZero } from "./TransferCallActionUpdateParamsActionTriggerZero";
import { Undefined } from "./Undefined";

export const TransferCallActionUpdateParamsActionTrigger: core.serialization.Schema<
    serializers.TransferCallActionUpdateParamsActionTrigger.Raw,
    Vocode.TransferCallActionUpdateParamsActionTrigger
> = core.serialization.undiscriminatedUnion([TransferCallActionUpdateParamsActionTriggerZero, Undefined]);

export declare namespace TransferCallActionUpdateParamsActionTrigger {
    type Raw = TransferCallActionUpdateParamsActionTriggerZero.Raw | Undefined.Raw;
}
