/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { TransferCallConfig } from "./TransferCallConfig";
import { TransferCallActionParamsActionTrigger } from "./TransferCallActionParamsActionTrigger";

export const TransferCallActionParams: core.serialization.ObjectSchema<
    serializers.TransferCallActionParams.Raw,
    Vocode.TransferCallActionParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("action_transfer_call"),
    config: TransferCallConfig,
    actionTrigger: core.serialization.property("action_trigger", TransferCallActionParamsActionTrigger.optional()),
});

export declare namespace TransferCallActionParams {
    interface Raw {
        type: "action_transfer_call";
        config: TransferCallConfig.Raw;
        action_trigger?: TransferCallActionParamsActionTrigger.Raw | null;
    }
}
