/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const TwilioTelephonyMetadata: core.serialization.ObjectSchema<
    serializers.TwilioTelephonyMetadata.Raw,
    Vocode.TwilioTelephonyMetadata
> = core.serialization.object({
    type: core.serialization.stringLiteral("telephony_metadata_twilio"),
    callSid: core.serialization.property("call_sid", core.serialization.string().optional()),
    callStatus: core.serialization.property("call_status", core.serialization.string().optional()),
    transferCallSid: core.serialization.property("transfer_call_sid", core.serialization.string().optional()),
    transferCallStatus: core.serialization.property("transfer_call_status", core.serialization.string().optional()),
    conferenceSid: core.serialization.property("conference_sid", core.serialization.string().optional()),
});

export declare namespace TwilioTelephonyMetadata {
    interface Raw {
        type: "telephony_metadata_twilio";
        call_sid?: string | null;
        call_status?: string | null;
        transfer_call_sid?: string | null;
        transfer_call_status?: string | null;
        conference_sid?: string | null;
    }
}
