/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { TwilioAccountConnectionUpdateParamsCredentials } from "./TwilioAccountConnectionUpdateParamsCredentials";

export const TwilioAccountConnectionUpdateParams: core.serialization.ObjectSchema<
    serializers.TwilioAccountConnectionUpdateParams.Raw,
    Vocode.TwilioAccountConnectionUpdateParams
> = core.serialization.object({
    credentials: TwilioAccountConnectionUpdateParamsCredentials.optional(),
    type: core.serialization.stringLiteral("account_connection_twilio"),
});

export declare namespace TwilioAccountConnectionUpdateParams {
    interface Raw {
        credentials?: TwilioAccountConnectionUpdateParamsCredentials.Raw | null;
        type: "account_connection_twilio";
    }
}
