/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { TwilioCredentials } from "./TwilioCredentials";
import { Undefined } from "./Undefined";

export const TwilioAccountConnectionUpdateParamsCredentials: core.serialization.Schema<
    serializers.TwilioAccountConnectionUpdateParamsCredentials.Raw,
    Vocode.TwilioAccountConnectionUpdateParamsCredentials
> = core.serialization.undiscriminatedUnion([TwilioCredentials, Undefined]);

export declare namespace TwilioAccountConnectionUpdateParamsCredentials {
    type Raw = TwilioCredentials.Raw | Undefined.Raw;
}
