/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { PineconeVectorDatabase } from "./PineconeVectorDatabase";

export const VectorDatabasePage: core.serialization.ObjectSchema<
    serializers.VectorDatabasePage.Raw,
    Vocode.VectorDatabasePage
> = core.serialization.object({
    items: core.serialization.list(PineconeVectorDatabase),
    page: core.serialization.number(),
    size: core.serialization.number(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    total: core.serialization.number(),
    totalIsEstimated: core.serialization.property("total_is_estimated", core.serialization.boolean()),
});

export declare namespace VectorDatabasePage {
    interface Raw {
        items: PineconeVectorDatabase.Raw[];
        page: number;
        size: number;
        has_more: boolean;
        total: number;
        total_is_estimated: boolean;
    }
}
