/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const VocodeVoice: core.serialization.ObjectSchema<serializers.VocodeVoice.Raw, Vocode.VocodeVoice> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        type: core.serialization.stringLiteral("voice_vocode"),
        voiceId: core.serialization.property("voice_id", core.serialization.stringLiteral("joe")),
    });

export declare namespace VocodeVoice {
    interface Raw {
        id: string;
        user_id: string;
        type: "voice_vocode";
        voice_id: "joe";
    }
}
