/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { VocodeVoiceUpdateParamsVoiceId } from "./VocodeVoiceUpdateParamsVoiceId";

export const VocodeVoiceUpdateParams: core.serialization.ObjectSchema<
    serializers.VocodeVoiceUpdateParams.Raw,
    Vocode.VocodeVoiceUpdateParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("voice_vocode"),
    voiceId: core.serialization.property("voice_id", VocodeVoiceUpdateParamsVoiceId.optional()),
});

export declare namespace VocodeVoiceUpdateParams {
    interface Raw {
        type: "voice_vocode";
        voice_id?: VocodeVoiceUpdateParamsVoiceId.Raw | null;
    }
}
