/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";

export const VocodeVoiceParams: core.serialization.ObjectSchema<
    serializers.VocodeVoiceParams.Raw,
    Vocode.VocodeVoiceParams
> = core.serialization.object({
    type: core.serialization.stringLiteral("voice_vocode"),
    voiceId: core.serialization.property("voice_id", core.serialization.stringLiteral("joe")),
});

export declare namespace VocodeVoiceParams {
    interface Raw {
        type: "voice_vocode";
        voice_id: "joe";
    }
}
