/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { AzureVoiceUpdateParams } from "./AzureVoiceUpdateParams";
import { ElevenLabsVoiceUpdateParams } from "./ElevenLabsVoiceUpdateParams";
import { PlayHtVoiceUpdateParams } from "./PlayHtVoiceUpdateParams";
import { RimeVoiceUpdateParams } from "./RimeVoiceUpdateParams";
import { VocodeVoiceUpdateParams } from "./VocodeVoiceUpdateParams";

export const VoiceUpdateParamsRequest: core.serialization.Schema<
    serializers.VoiceUpdateParamsRequest.Raw,
    Vocode.VoiceUpdateParamsRequest
> = core.serialization.undiscriminatedUnion([
    AzureVoiceUpdateParams,
    ElevenLabsVoiceUpdateParams,
    PlayHtVoiceUpdateParams,
    RimeVoiceUpdateParams,
    VocodeVoiceUpdateParams,
]);

export declare namespace VoiceUpdateParamsRequest {
    type Raw =
        | AzureVoiceUpdateParams.Raw
        | ElevenLabsVoiceUpdateParams.Raw
        | PlayHtVoiceUpdateParams.Raw
        | RimeVoiceUpdateParams.Raw
        | VocodeVoiceUpdateParams.Raw;
}
