/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const WebhookUpdateParamsUrl: core.serialization.Schema<
    serializers.WebhookUpdateParamsUrl.Raw,
    Vocode.WebhookUpdateParamsUrl
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Undefined]);

export declare namespace WebhookUpdateParamsUrl {
    type Raw = string | Undefined.Raw;
}
