/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { HttpMethod } from "./HttpMethod";
import { Undefined } from "./Undefined";

export const WebhookUpdateParamsMethod: core.serialization.Schema<
    serializers.WebhookUpdateParamsMethod.Raw,
    Vocode.WebhookUpdateParamsMethod
> = core.serialization.undiscriminatedUnion([HttpMethod, Undefined]);

export declare namespace WebhookUpdateParamsMethod {
    type Raw = HttpMethod.Raw | Undefined.Raw;
}
