/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { EventType } from "./EventType";
import { Undefined } from "./Undefined";

export const WebhookUpdateParamsSubscriptions: core.serialization.Schema<
    serializers.WebhookUpdateParamsSubscriptions.Raw,
    Vocode.WebhookUpdateParamsSubscriptions
> = core.serialization.undiscriminatedUnion([core.serialization.list(EventType), Undefined]);

export declare namespace WebhookUpdateParamsSubscriptions {
    type Raw = EventType.Raw[] | Undefined.Raw;
}
