/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../../index";

/**
 * @example
 *     {
 *         fromNumber: "from_number",
 *         toNumber: "to_number",
 *         agent: "agent"
 *     }
 */
export interface CreateCallRequest {
    fromNumber: string;
    toNumber: string;
    agent: Vocode.CreateCallRequestAgent;
    onNoHumanAnswer?: Vocode.CreateCallRequestOnNoHumanAnswer;
    runDoNotCallDetection?: boolean;
    hipaaCompliant?: boolean;
    context?: Record<string, string | undefined>;
    telephonyParams?: Record<string, string | undefined>;
}
