/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListCallsRequest {
    page?: number;
    size?: number;
    sortColumn?: string;
    sortDesc?: boolean;
}
