/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vocode from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCallRequestOnNoHumanAnswer: core.serialization.Schema<
    serializers.CreateCallRequestOnNoHumanAnswer.Raw,
    Vocode.CreateCallRequestOnNoHumanAnswer
> = core.serialization.enum_(["continue", "hangup"]);

export declare namespace CreateCallRequestOnNoHumanAnswer {
    type Raw = "continue" | "hangup";
}
