/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Vocode from "../../../../api/index";
import * as core from "../../../../core";
import { CreateCallAgentParams } from "../../../types/CreateCallAgentParams";

export const CreateCallRequestAgent: core.serialization.Schema<
    serializers.CreateCallRequestAgent.Raw,
    Vocode.CreateCallRequestAgent
> = core.serialization.undiscriminatedUnion([core.serialization.string(), CreateCallAgentParams]);

export declare namespace CreateCallRequestAgent {
    type Raw = string | CreateCallAgentParams.Raw;
}
