/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Vocode from "../../../../../api/index";
import * as core from "../../../../../core";
import { BuyPhoneNumberRequestTelephonyProvider } from "../../types/BuyPhoneNumberRequestTelephonyProvider";
import { BuyPhoneNumberRequestInboundAgent } from "../../types/BuyPhoneNumberRequestInboundAgent";

export const BuyPhoneNumberRequest: core.serialization.Schema<
    serializers.BuyPhoneNumberRequest.Raw,
    Vocode.BuyPhoneNumberRequest
> = core.serialization.object({
    areaCode: core.serialization.property("area_code", core.serialization.string().optional()),
    telephonyProvider: core.serialization.property(
        "telephony_provider",
        BuyPhoneNumberRequestTelephonyProvider.optional()
    ),
    telephonyAccountConnection: core.serialization.property(
        "telephony_account_connection",
        core.serialization.string().optional()
    ),
    inboundAgent: core.serialization.property("inbound_agent", BuyPhoneNumberRequestInboundAgent.optional()),
});

export declare namespace BuyPhoneNumberRequest {
    interface Raw {
        area_code?: string | null;
        telephony_provider?: BuyPhoneNumberRequestTelephonyProvider.Raw | null;
        telephony_account_connection?: string | null;
        inbound_agent?: BuyPhoneNumberRequestInboundAgent.Raw | null;
    }
}
